---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: esphome
  name: esphome-pvc
  namespace: esphome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
  storageClassName: longhorn
